<script lang="ts">
  import { stripTrailingSlash } from '../lib/pagefind';
  import { withBase } from '../lib/withBase';
  import ClearButton from './ClearButton.svelte';

  export let surface: 'projects' | 'notes';

  const isDev = import.meta.env.DEV;

  let query = '';
  let results: Array<{ url: string; title: string; excerpt: string }> = [];
  let loading = false;
  let searched = false;
  let pagefind: any = null;

  const CONTENT_SELECTOR = '.page-content';

  function toggleContentVisibility(active: boolean) {
    const content = document.querySelector(CONTENT_SELECTOR);
    if (content) {
      content.classList.toggle('search-active', active);
    }
  }

  async function loadPagefind() {
    if (!pagefind) {
      try {
        // Pagefind JS is generated by `pagefind --site dist` in the
        // postbuild step — it doesn't exist at Vite bundle time. The
        // dynamic URL construction prevents Vite's static analysis from
        // attempting to resolve the module at build time.
        const pagefindPath = withBase('pagefind/pagefind.js');
        pagefind = await import(/* @vite-ignore */ pagefindPath);
        await pagefind.init();
      } catch {
        return null;
      }
    }
    return pagefind;
  }

  let debounceTimer: ReturnType<typeof setTimeout>;

  function handleInput() {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(performSearch, 250);
  }

  async function performSearch() {
    const q = query.trim();
    if (!q) {
      results = [];
      searched = false;
      toggleContentVisibility(false);
      return;
    }

    loading = true;
    const pf = await loadPagefind();
    if (!pf) {
      loading = false;
      return;
    }

    const searchResult = await pf.search(q, {
      filters: { surface },
    });

    const loaded = await Promise.all(
      searchResult.results.slice(0, 50).map(async (r: any) => {
        const data = await r.data();
        return {
          url: stripTrailingSlash(data.url),
          title: data.meta?.title ?? data.url,
          excerpt: data.excerpt ?? '',
        };
      }),
    );

    results = loaded;
    searched = true;
    loading = false;
    toggleContentVisibility(true);
  }

  function clearSearch() {
    query = '';
    results = [];
    searched = false;
    toggleContentVisibility(false);
  }
</script>

<div class="search-island">
  {#if isDev}
    <div class="search-input-wrapper">
      <input
        type="text"
        class="search-input disabled"
        placeholder="Search {surface}..."
        disabled
        aria-label="Search {surface}"
      />
    </div>
    <p class="search-dev-notice">Search requires a production build — npm run build && npm run preview</p>
  {:else}
    <div class="search-input-wrapper">
      <input
        type="text"
        class="search-input"
        placeholder="Search {surface}..."
        bind:value={query}
        on:input={handleInput}
        aria-label="Search {surface}"
      />
      {#if query}
        <ClearButton on:click={clearSearch} />
      {/if}
    </div>

    {#if searched}
      <div class="search-results" role="region" aria-label="Search results">
        {#if loading}
          <p class="search-status">Searching...</p>
        {:else if results.length === 0}
          <p class="search-status">No results found.</p>
        {:else}
          <p class="search-status">{results.length} result{results.length !== 1 ? 's' : ''}</p>
          <ol class="results-list">
            {#each results as result (result.url)}
              <li class="result-entry">
                <a class="result-title" href={result.url}>{result.title}</a>
                {#if result.excerpt}
                  <p class="result-excerpt">{@html result.excerpt}</p>
                {/if}
              </li>
            {/each}
          </ol>
        {/if}
      </div>
    {/if}
  {/if}
</div>

<style>
  .search-island {
    margin-bottom: var(--space-6);
  }

  .search-input-wrapper {
    position: relative;
    display: flex;
    align-items: center;
  }

  .search-input {
    width: 100%;
    background: transparent;
    border: 1px solid var(--color-border);
    border-radius: 2px;
    color: var(--color-text-primary);
    font-family: var(--font-family-ui);
    font-size: var(--font-size-2);
    padding: var(--space-3) var(--space-4);
    padding-right: var(--space-8);
    outline: none;
    transition: border-color var(--duration-fast) var(--ease-standard);
  }

  .search-input::placeholder {
    color: var(--color-text-muted);
  }

  .search-input:focus {
    border-color: var(--color-accent);
  }

  .search-input.disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .search-dev-notice {
    margin: var(--space-2) 0 0;
    color: var(--color-text-muted);
    font-size: var(--font-size-1);
    font-family: var(--font-family-mono);
  }

  .search-results {
    margin-top: var(--space-4);
  }

  .search-status {
    margin: 0;
    color: var(--color-text-muted);
    font-size: var(--font-size-1);
  }

  .results-list {
    list-style: none;
    margin: var(--space-4) 0 0;
    padding: 0;
  }

  .result-entry {
    padding: var(--space-4) 0;
    border-top: 1px solid var(--color-border);
  }

  .result-entry:first-child {
    border-top: none;
  }

  .result-title {
    display: block;
    font-size: var(--font-size-3);
    font-weight: 600;
    color: var(--color-text-primary);
    text-decoration: none;
    transition: color var(--duration-fast) var(--ease-standard);
  }

  .result-title:hover,
  .result-title:focus-visible {
    color: var(--color-accent);
  }

  .result-title:focus-visible {
    outline: 2px solid var(--color-focus-ring);
    outline-offset: 2px;
  }

  .result-excerpt {
    margin: var(--space-2) 0 0;
    color: var(--color-text-muted);
    font-size: var(--font-size-1);
    line-height: 1.5;
  }

  .result-excerpt :global(mark) {
    background: var(--color-accent-subtle);
    color: var(--color-text-primary);
    padding: 0 2px;
  }
</style>
